### ISSUE TITLE
Missing theme option

### ISSUE THREAD

**Issue by emwee** [dbushell/Pikaday#293] opened 2015-04-17 14:29 UTC
Hi,

It seems that the theme option has been removed from version 1.3.2, I was wondering if this is on purpose?

**Comment by destan** [comment] 2015-04-21 09:05
Yeah I was struggling with this one recently. It seems like a regression because documentation and examples still cover it. Anybody? @rikkert 

By the way it's impossible to find the version of Pikaday used in examples, it would be better to include version number as comment in js files. For example, no version number: http://dbushell.github.io/Pikaday/examples/theme.html

**Comment by rikkert** [comment] 2015-04-21 20:36
More likely not yet released instead of removed?
Examples run with the master version of pikaday.

**Closed by rikkert** 2015-04-21 20:36 UTC
