### ISSUE TITLE
Chrome causing Pikaday to lose focus

### ISSUE THREAD

**Issue by GageGaskins** [dbushell/Pikaday#366] opened 2015-07-20 18:44 UTC
I've been trying to use 1.3.3 for the date range options, however whenever I try to select anything within the Pikaday div, it interprets the click as an self._onInputFocus rather than a self.click. Not sure what might be causing it, and the only other plugin running on the page is jQuery.

**Comment by nathancahill** [comment] 2015-07-20 19:18
Do you see this behavior in 1.3.2? Can you make a JSFiddle that replicates the issue?

**Comment by GageGaskins** [comment] 2015-07-20 19:54
The behavior doesn't happen on 1.3.2. Currently unable to make a JSFiddle that replicates it so I'll look into it some more. Possibly the page I'm on has a handler associated with the field that takes focus away when it's not supposed to.

**Comment by pgoggijr** [comment] 2015-07-22 14:34
I see this issue in chrome as well.  Looks fine on latest IE and FF.

http://jsfiddle.net/phzjk96g/1/

**Comment by duizendnegen** [comment] 2015-07-27 19:28
Copy that. It seems to have to do with `addEvent(self.el, 'ontouchend' in document ? 'touchend' : 'mousedown', self._onMouseDown, true);` (line 553)
If you change it to `addEvent(self.el, 'onmousedown' in document ? 'mousedown' : 'touchend', self._onMouseDown, true);` it works fine (but I'm expecting pain on mobile). Seems like Chrome added the touchend event on a recent version.

Seems like a duplicate of #276

**Closed** 2015-08-24 09:23 UTC
