### ISSUE TITLE
Pikaday Demo not working with Chrome v45

### ISSUE THREAD

**Issue by mkoshy** [dbushell/Pikaday#406] opened 2015-09-17 12:37 UTC
The demo does not allow the scrolling on months or selection of a date when this version of Chrome is used,

**Comment by Bucky24** [comment] 2015-09-17 15:39
Having the same issue both with demo and when using pikaday on my own site. Also using chrome v45. From what I can tell, the _onClick handler seems to be firing fine, but just keeps getting parent elements of whatever is clicked until it finds the pika-single div, then closes itself without doing anything else.

**Comment by alexcroox** [comment] 2015-09-18 07:50
Wondered what I'd changed in my code! Not working on Chrome this week either for me. Works fine in other browsers.

**Comment by jopotts** [comment] 2015-10-16 14:07
I have reports of people 'not being able to select a date' or 'go back' (previous month arrow I think) on the following browsers (and perhaps others):

http://www.whatsmybrowser.org/b/R523JZ9 - Chrome 45 on Win 8.1
http://www.whatsmybrowser.org/b/C3BH5AA - IE11 on Win 7

Works for me:

http://whatsmybrowser.org/b/0Y34ZW3 - Chrome 45 on OSX 10.11

I've failed to reproduce the issue myself, but it's a pretty serious bug. :-( I'll have a look into it (although not being able to reproduce makes it tough).

Has anyone else tried to fix this or have any pointers on what it might be?

Thanks

**Comment by Seldaek** [comment] 2015-10-16 14:43
I have successfully "fixed" this from the outside (as I rather not run a patched lib..) using this after initializing pikaday:

```
        if ('ontouchend' in document) {
            this.pikaday.el.addEventListener('mousedown', this.pikaday._onMouseDown, true);
        }
```

I suspect it might cause issues like double-trigger of every action whenever the bug is fixed in pikaday though, so you wanna be careful when upgrading if you implement this. Also don't forget to removeEventListener before destroying pikaday.

**Closed** 2015-11-02 09:43 UTC

**Comment by neocow** [comment] 2015-11-09 01:21
Thanks for that fix, Seldaek.  We didn't know why this wasn't firing correctly, didn't attribute it to having touchscreen laptops...
